<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VehicleModel;
use App\Models\VehicleBrand;

class VehicleModelSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Honda Motor' => [
                'Honda Vario 125',
                'Honda Scoopy',
                'Honda Beat',
                'Honda PCX160',
                'Honda Beat Street',
                'Honda CRF150L',
                'Honda Stylo 160',
                'Honda Vario 160',
                'Honda ADV 160',
                'Honda Supra GTR 150',
                'Honda Sonic 150R',
                'Honda Genio',
                'Honda Revo',
                'Honda CBR150R',
                'Honda CBR250RR',
                'Honda Supra X 125 FI',
                'Honda CB150 Verza',
                'Honda CB150R Streetfire',
                'Honda CRF250Rally',
                'Honda Forza 250',
                'Honda CB150X',
                'Honda EM1 E',
                'Honda CB650R',
                'Honda CRF250L',
                'Honda Rebel',
                'Honda CB500X',
                'Honda Super Cub C125',
                'Honda ST125 Dax',
                'Honda CT125',
                'Honda CBR1000RR-R',
                'Honda CRF1100L Africa Twin',
                'Honda XL750 Transalp',
                'Honda Monkey',
                'Honda ICON e:',
                'Honda CUV e:',
                'Honda Goldwing',
                'HondaRebel 1100',
            ],
            'Yamaha' => [
                'Yamaha Jupiter Z1',
                'Yamaha Fino 125',
                'Yamaha NMAX',
                'Yamaha Fazzio',
                'Yamaha Mio M3 125',
                'Yamaha Aerox Connected',
                'Yamaha WR155 R',
                'Yamaha MX King',
                'Yamaha Nmax Turbo',
                'Yamaha Grand Filano Hybrid Connected',
                'Yamaha XRide 125',
                'Yamaha Nmax Connected',
                'Yamaha XSR 155',
                'Yamaha Vega Force',
                'Yamaha MT-25',
                'Yamaha Aerox Connected ABS',
                'Yamaha Xmax Connected',
                'Yamaha Gear 125',
                'Yamaha R15 Connected',
                'Yamaha Vixion',
                'Yamaha Lexi LX 155',
                'Yamaha FreeGo',
                'Yamaha MT-15',
                'Yamaha Vixion R',
                'Yamaha YZ125X',
                'Yamaha YZF R25',
                'Yamaha Freego Connected',
                'Yamaha YZ250',
                'Yamaha Aerox Alpha',
                'Yamaha Gear Ultima',
            ],
            'Suzuki Motor' => [
                'Suzuki Satria F150',
                'Suzuki GSX R150',
                'Suzuki Burgman Street 125 EX',
                'Suzuki NEX II',
                'Suzuki GSX S150',
                'Suzuki NEX Crossover',
                'Suzuki Address',
                'Suzuki V-Strom 250 SX',
                'Suzuki Avenis',
                'Suzuki Gixxer SF 250',
            ],
            'Kawasaki' => [
                'Kawasaki KX 65',
                'Kawasaki W175',
                'Kawasaki Ninja ZX-25R',
                'Kawasaki Ninja 250',
                'Kawasaki KLX 150 SM',
                'Kawasaki KLX 150',
                'Kawasaki D-Tracker',
                'Kawasaki KLX 140R',
                'Kawasaki Z125 PRO',
                'Kawasaki KLX 150 SM SE',
                'Kawasaki Ninja ZX-25RR',
                'Kawasaki W175TR',
                'Kawasaki KLX 250',
                'Kawasaki Z900',
                'Kawasaki Ninja H2',
                'Kawasaki Z1000',
                'Kawasaki Ninja ZX-4RR',
                'Kawasaki Versys X 250',
                'Kawasaki KLX110R',
                'Kawasaki Versys 1000',
                'Kawasaki KLX 230',
                'Kawasaki KLX 230 SM',
                'Kawasaki Vulcan S',
                'Kawasaki NINJA E-1',
                'Kawasaki Versys 650',
                'Kawasaki KLX 150 S',
                'Kawasaki KX 112',
                'Kawasaki KX 250',
                'Kawasaki KX 450',
                'Kawasaki Ninja ZX-6R ABS',
                'Kawasaki ELIMINATOR',
                'Kawasaki Z900RS',
                'Kawasaki Ninja ZX10-R',
                'Kawasaki KX 85',
                'Kawasaki Z900RS CAFE',
                'Kawasaki Stockman',
                'Kawasaki Z E-1',
                'Kawasaki KX 250X',
                'Kawasaki KX 450X',
                'Kawasaki W800',
                'Kawasaki Z900 SE',
                'Kawasaki W230',
                'Kawasaki MEGURO S1',
            ],
            'Benelli' => [
                'Benelli Zafferano 250',
                'Benelli Motobi 200 Evo',
                'Benelli Patagonian Eagle 250',
                'Benelli Motobi 200',
                'Benelli Motobi 152',
                'Benelli Patagonian 250 EFI',
                'Benelli Panarea 125',
                'Benelli TNT 135',
                'Benelli TRK251',
                'Benelli Imperiale 400',
                'Benelli TRK 502X',
                'Benelli Leoncino 250',
                'Benelli 502C',
                'Benelli TNT 249S',
                'Benelli TNT 600i',
                'Benelli Dong',
                'Benelli TNT 1130',
                'Benelli Leoncino 500',
            ],
            'KTM' => [
                'KTM RC 390',
                'KTM Duke 200',
                'KTM 450 SX-F Factory Edition',
                'KTM RC 200',
                'KTM 250 SX-F Troy Lee Designs',
                'KTM Duke 390',
                'KTM 250 Adventure',
                'KTM 300 EXC Hardenduro',
                'KTM RC 250',
                'KTM 390 Adventure',
                'KTM Duke 250',
                'KTM 300 XC-W Hardenduro',
                'KTM 890 Duke R',
                'KTM Brabus 1300 R Masterpiece Edition',
                'KTM 890 Adventure R Rally',
                'KTM 890 Adventure',
                'KTM 890 SMT',
            ],
            'TVS' => [
                'TVS Dazz',
                'TVS Neo XR',
                'TVS XL 100',
                'TVS Rockz',
                'TVS Callisto',
                'TVS Ronin',
                'TVS Max 125 Semi Trail',
                'TVS Max 125 Sport',
                'TVS Ntorq 125',
                'TVS iQube S',
            ],
            'Viar' => [
                'Viar Cross X 100 Mini Trail',
                'Viar Cross X 70 Mini Trail',
                'Viar EV1',
                'Viar ER1',
                'Viar NX',
                'Viar V3',
                'Viar U3',
                'Viar C3X',
                'Viar Caraka',
                'Viar A2',
                'Viar Akasha3',
                'Viar UNO3',
                'Viar Q1',
                'Viar N1',
                'Viar CrossX 150DB',
                'Viar UNO4',
            ],
            'Vespa' => [
                'Vespa Sprint',
                'Vespa LX',
                'Vespa Primavera',
                'Vespa GTS 150',
                'Vespa GTS Super Sport 150',
                'Vespa GTV',
                'Vespa ELETTRICA',
                'Vespa GTS 300 Super Tech',
                'Vespa 946 Dragon',
            ],
            'Royal Enfield' => [
                'Royal Enfield Classic 350',
                'Royal Enfield Meteor',
                'Royal Enfield Himalayan',
                'Royal Enfield Hunter 350',
                'Royal Enfield Interceptor 650',
                'Royal Enfield Continental GT 650',
                'Royal Enfield Super Meteor 650',
                'Royal Enfield Bullet 350',
                'Royal Enfield Shotgun 650',
                'Royal Enfield Scram 411',
                'Royal Enfield Guerrilla 450',
                'Royal Enfield Himalayan 450',
            ],
            'BMW Motor' => [
                'BMW R Nine T',
                'BMW G 310 R',
                'BMW G 310 GS',
                'BMW S 1000 RR',
                'BMW R Nine T Scrambler',
                'BMW S 1000 XR',
                'BMW F 900 R',
                'BMW K 1600 B',
                'BMW R 1250 GS',
                'BMW M 1000 RR',
                'BMW C 400 X',
                'BMW R 1300 GS',
                'BMW R 1250 GS Adventure',
                'BMW R Nine T Urban G/S',
                'BMW K 1600 B Grand America',
                'BMW C 400 GT',
                'BMW R 18 Classic',
                'BMW F 850 GS Adventure',
                'BMW R 12',
                'BMW R12 S',
                'BMW CE 04',
                'BMW R 18',
                'BMW CE 02',
                'BMW R 12 NineT',
                'BMW F 900 GS',
                'BMW M 1000 R',
                'BMW R 1300 GS Adventure',
            ],
            'Ducati' => [
                'Ducati Panigale V4',
                'Ducati MultiStrada',
                'Ducati Panigale',
                'Ducati Monster',
                'Ducati Hypermotard 950',
                'Ducati Multistrada 1260',
                'Ducati Diavel',
                'Ducati XDiavel',
                'Ducati Streetfighter V4',
                'Ducati SuperSport 950',
                'Ducati Desert X',
            ],
            'Triumph' => [
                'Triumph Bonneville T120',
                'Triumph Bonneville T100',
                'Triumph Bonneville Bobber',
                'Triumph Speed Twin',
                'Triumph Tiger 900',
                'Triumph Rocket 3',
                'Triumph Scrambler 1200',
                'Triumph Bonneville Speedmaster',
                'Triumph Speed Twin 900',
                'Triumph Tiger 1200',
                'Triumph Tiger Sport 660',
                'Triumph Speed 400',
                'Triumph Scrambler 400 X',
                'Triumph Scrambler 900',
                'Triumph Speed Triple 1200 RR',
                'Triumph Daytona 660',
            ],
            'Bajaj' => [
                'Bajaj Rouser',
            ],
            'SYM' => [
                'SYM Maxsym 400i',
                'SYM MAXSYM TL',
            ],
            'Harley Davidson' => [
                'Harley Davidson Street Bob',
                'Harley Davidson Fat Bob',
                'Harley Davidson Street Glide',
                'Harley Davidson Fat Boy',
                'Harley Davidson Road Glide',
                'Harley Davidson Breakout 117',
                'Harley Davidson Sportster',
                'Harley Davidson Road King Special',
                'Harley Davidson Hydra-Glide Revival',
                'Harley Davidson Nightster',
                'Harley Davidson Softail',
                'Harley Davidson Heritage Classic',
                'Harley Davidson Ultra Limited',
                'Harley Davidson Low Rider',
                'Harley Davidson Pan America 1250 Special',
            ],
            'Husqvarna' => [
                'Husqvarna Svartpilen 401',
                'Husqvarna TC 250',
                'Husqvarna TE 300',
                'Husqvarna FE 250',
                'Husqvarna FC 250',
                'Husqvarna TC 50',
                'Husqvarna FE 350',
                'Husqvarna TC 65',
                'Husqvarna FC 350',
                'Husqvarna FS 450',
                'Husqvarna FE 450',
                'Husqvarna FC 450',
                'Husqvarna Norden 901',
                'Husqvarna TE 250',
                'Husqvarna Enduro 701',
                'Husqvarna TC 85 19/16',
                'Husqvarna FE 501',
                'Husqvarna Vitpilen 401',
                'Husqvarna Vitpilen 701',
                'Husqvarna Supermoto 701',
                'Husqvarna Svartpilen 250',
                'Husqvarna TX 300',
                'Husqvarna Svartpilen 701',
            ],
            'Cleveland CycleWerks' => [
                'Cleveland CycleWerks Heist',
                'Cleveland CycleWerks Misfit',
                'Cleveland CycleWerks Ace 250 Twin',
                'Cleveland CycleWerks Ace 400',
                'Cleveland CycleWerks Ace 250',
            ],
            'Kymco' => [
                'Kymco Racing King 150i',
                'Kymco Downtown 250i',
                'Kymco Like 150i',
                'Kymco X-Town 250i',
            ],
            'Aprilia' => [
                'Aprilia RS 660',
                'Aprilia SR-GT 200',
                'Aprilia SR-GT SPORT 200',
                'Aprilia Tuono 660',
                'Aprilia Tuareg 660',
                'Aprilia SR-GT Replica',
            ],
            'Piaggio' => [
                'Piaggio Medley',
                'Piaggio MP3 300',
            ],
            'Peugeot Motor' => [
                'Peugeot Citystar 200i',
                'Peugeot Django 150',
                'Peugeot Metropolis 400i',
            ],
            'Moto Guzzi' => [
                'Moto Guzzi V100 Mandello',
                'Moto Guzzi V85 TT Travel',
                'Moto Guzzi V7 Stone',
                'Moto Guzzi Stelvio',
            ],
            'Diablo' => [
                'Diablo 200x',
            ],
            'Gesits' => [
                'Gesits Electric',
                'Gesits Raya',
                'Gesits G1 DLX',
                'Gesits Garuda',
            ],
            'SM Sport' => [
                'SM Sport V16',
                'SM Sport V16 Plus',
                'SM Sport GY 150 Aries',
                'SM Sport SM3',
                'SM Sport SM Classic',
                'SM Sport GY 150',
                'SM Sport E-Classic',
                'SM Sport SM Master 200',
            ],
            'ECGO' => [
                'ECGO 2',
            ],
            'United' => [
                'United SC121',
                'United T1800',
                'United MX 1200',
                'United TX1800',
                'United TX3000',
                'United C2000',
                'United MT1500',
                'United Avand SC122',
                'United Avand SL150',
                'United Milano V1',
            ],
            'Selis' => [
                'Selis E-Max',
                'Selis Neo Scootic',
                'Selis Rinjani',
                'Selis Gemini',
                'Selis Bangau',
                'Selis Mino',
                'Selis Flamingo',
                'Selis Agats',
                'Selis Kenari',
                'Selis Komodo',
                'Selis Sanur',
                'Selis Anyer',
                'Selis Galaxy',
                'Selis Hippo',
            ],
            'BF Goodrich' => [
                'BF Goodrich CG',
                'BF Goodrich BEE',
                'BF Goodrich Q7',
            ],
            'Qooder' => [
                'Qooder Qooder',
            ],
            'Royal Alloy' => [
                'Royal Alloy GP150',
                'Royal Alloy GT2 Series',
            ],
            'Italjet' => [
                'Italjet Dragster',
            ],
            'Keeway' => [
                'Keeway V250 FI',
                'Keeway SCR 250V',
                'Keeway Shiny 150',
                'Keeway Gleiten 125',
            ],
            'Volta' => [
                'Volta 401',
                'Volta Mandala',
                'Volta Virgo',
            ],
            'Alva' => [
                'Alva CERVO',
                'Alva One',
                'Alva One Xp',
                'Alva N3',
            ],
            'Segway' => [
                'Segway E200P One',
                'Segway E Series',
            ],
            'Treeletrik' => [
                'Treeletrik T-70',
            ],
            'Polytron Motor' => [
                'Polytron Fox-R',
                'Polytron Fox 500',
            ],
            'Charged' => [
                'Charged Rimau',
                'Charged Rimau S',
                'Charged Maleo',
                'Charged Anoa',
            ],
            'Yadea' => [
                'Yadea T9',
                'Yadea E8S Pro',
                'Yadea Sparta',
                'Yadea G6',
                'Yadea Dingding',
                'Yadea Minion',
                'Yadea X-Bull',
                'Yadea Velax',
            ],
            'Scomadi' => [
                'Scomadi Technica 200i',
                'Scomadi Technica 150i',
                'Scomadi Technica 200i Adventure',
                'Scomadi Turismo Piccolo 150i',
                'Scomadi Turismo Technica 200i',
                'Scomadi Technica 200i Urban',
                'Scomadi Turismo Technica 200W',
            ],
            'LISGO' => [
                'LISGO S3',
                'LISGO S1',
                'LISGO CT-1',
                'LISGO L1',
                'LISGO A8',
                'LISGO A9',
                'LISGO CT-6',
                'LISGO L3',
            ],
            'Savart' => [
                'Savart S-1P Insignia',
            ],
            'KOOL' => [
                'KOOL Bima',
                'KOOL Arjuna',
                'KOOL Chakra',
                'KOOL Kirana',
            ],
            'Wmoto' => [
                'Wmoto Greta',
                'Wmoto Morbius',
                'Wmoto Letbe Neon',
                'Wmoto Draco',
                'Wmoto Neutron',
            ],
            'CFMoto' => [
                'CFMoto Papio XO-1',
                'CFMoto Papio XO-2',
                'CFMoto 450 MT',
                'CFMoto CLC450',
                'CFMoto 500 SR-Voom',
                'CFMoto 250 CLC',
                'CFMoto 650MT',
                'CFMoto 800 MT',
                'CFMoto Zeeho AE8',
                'CFMoto 250SR',
                'CFMoto 450 SR',
                'CFMoto Zeeho AE6',
                'CFMoto Zeeho City Sport',
                'CFMoto 1250 TR-G',
                'CFMoto 250 CL-X',
            ],
            'Rakata Motorcycle' => [
                'Rakata Motorcycle NX8',
                'Rakata Motorcycle S9',
                'Rakata Motorcycle X5',
                'Rakata Motorcycle NX3',
            ],
            'Vmove' => [
                'Vmove keren stardust',
            ],
            'ION' => [
                'ION Mobility M1-s',
            ],
            'ZPT' => [
                'ZPT NYX',
                'ZPT Nimbuzz',
            ],
            'Pacific' => [
                'Pacific VIRGO 1.2 LB',
                'Pacific VALERO RX 7.0',
                'Pacific MAGENTA',
            ],
            'Uwinfly' => [
                'Uwinfly T5',
                'Uwinfly D70',
                'Uwinfly T3s Pro',
                'Uwinfly D60',
                'Uwinfly T3 Pro',
                'Uwinfly M70',
                'Uwinfly X6',
                'Uwinfly T3',
                'Uwinfly N9 Pro',
                'Uwinfly LN',
                'Uwinfly GT2',
                'Uwinfly R8P',
                'Uwinfly R8S',
                'Uwinfly R7S',
                'Uwinfly D8P',
                'Uwinfly D8S',
                'Uwinfly D7S',
            ],
            'Maka' => [
                'Maka Cavalry',
            ],
            'INDOMOBIL eMOTOR' => [
                'INDOMOBIL Adora',
            ],
            'QJ Motor' => [
                'QJ Motor SRK 800RR',
                'QJ Motor SRV 600V',
                'QJ Motor Fort 250',
                'QJ Motor SRV 250A',
            ],
            'Benda' => [
                'Benda NapoleonBob 250',
            ],
            'Sunra' => [
                'Sunra Legend',
                'Sunra Future',
                'Sunra Q5',
            ],
            'Toyota' => [
                'Toyota Calya',
                'Toyota Avanza',
                'Toyota Rush',
                'Toyota Agya',
                'Toyota Kijang Innova',
                'Toyota Raize',
                'Toyota Fortuner',
                'Toyota Hilux',
                'Toyota Veloz',
                'Toyota Yaris',
                'Toyota Kijang Innova Zenix Hybrid EV',
                'Toyota Kijang Innova Zenix',
                'Toyota Hiace',
                'Toyota Hilux Rangga',
                'Toyota Yaris Cross',
                'Toyota Alphard',
                'Toyota Land Cruiser',
                'Toyota Voxy',
                'Toyota Corolla Cross',
                'Toyota Vios',
                'Toyota Corolla Altis',
                'Toyota GR Supra',
                'Toyota GR 86',
                'Toyota GR Corolla',
                'Toyota Prius HEV',
                'Toyota bZ4X',
                'Toyota Vellfire HEV',
                'Toyota GR Yaris',
                'Toyota RAV4 PHEV',
                'Toyota Camry HEV',
            ],
            'Daihatsu' => [
                'Daihatsu Sigra',
                'Daihatsu Ayla',
                'Daihatsu Terios',
                'Daihatsu Gran Max PU',
                'Daihatsu Xenia',
                'Daihatsu Rocky',
                'Daihatsu Gran Max MB',
                'Daihatsu Luxio',
                'Daihatsu Sirion',
            ],
            'Honda Mobil' => [
                'Honda Brio',
                'Honda WR-V',
                'Honda BRV',
                'Honda HRV',
                'Honda CR-V',
                'Honda City Hatchback',
                'Honda Civic RS',
                'Honda Civic Type R',
                'Honda City',
                'Honda e:N1',
                'Honda Accord',
            ],
            'Mitsubishi' => [
                'Mitsubishi Xpander',
                'Mitsubishi L300',
                'Mitsubishi Pajero Sport',
                'Mitsubishi Xpander Cross',
                'Mitsubishi XForce',
                'Mitsubishi Triton',
                'Mitsubishi Pajero Sport Elite',
                'Mitsubishi L100 EV',
            ],
            'Suzuki Mobil' => [
                'Suzuki Ertiga',
                'Suzuki XL7',
                'Suzuki Jimny',
                'Suzuki Carry',
                'Suzuki S-Presso',
                'Suzuki Baleno',
                'Suzuki Grand Vitara',
                'Suzuki APV Arena',
                'Suzuki Ertiga Smart Hybrid',
                'Suzuki Jimny 5 Door',
            ],
            'Hyundai' => [
                'Hyundai Creta',
                'Hyundai Stargazer',
                'Hyundai Palisade',
                'Hyundai Stargazer X',
                'Hyundai Ioniq 5',
                'Hyundai Kona Electric',
                'Hyundai Ioniq 6',
                'Hyundai Staria',
                'Hyundai Ioniq 5 N',
                'Hyundai Santa Fe',
                'Hyundai Creta 2025',
                'Hyundai Venue',
                'Hyundai Tucson',
            ],
            'Wuling' => [
                'Wuling Formo',
                'Wuling Air EV',
                'Wuling Alvez',
                'Wuling Confero',
                'Wuling Binguo EV',
                'Wuling Cloud EV',
                'Wuling Cortez',
                'Wuling Almaz Hybrid',
                'Wuling Almaz RS',
                'Wuling Confero S',
                'Wuling Formo Max',
                'Wuling Cortez S',
            ],
            'Kia' => [
                'Kia Sonet',
                'Kia Carens',
                'Kia Grand Carnival',
                'Kia Carnival HEV',
                'Kia K2700',
                'Kia EV9',
                'Kia Seltos',
                'Kia EV6',
            ],
            'BMW Mobil' => [
                'BMW X1',
                'BMW M4 Coupe',
                'BMW 2 Series Gran Coupe',
                'BMW 5 Series Sedan',
                'BMW XM',
                'BMW X4',
                'BMW X5',
                'BMW i5',
                'BMW Z4',
                'BMW X3',
                'BMW iX',
                'BMW 3 Series Sedan',
                'BMW 4 Series Coupe',
                'BMW i7',
                'BMW iX1',
                'BMW i5 Touring',
                'BMW 4 Series Convertible',
                'BMW 7 Series Sedan',
                'BMW X6',
                'BMW X7',
                'BMW M4 Convertible',
                'BMW M3 Touring',
                'BMW 3 Series Touring',
                'BMW 2 Series Coupe',
                'BMW i4',
                'BMW X3 M',
                'BMW X4 M',
                'BMW M2 Coupe',
            ],
            'Mazda' => [
                'Mazda 2',
                'Mazda CX-3',
                'Mazda CX 9',
                'Mazda 3 Hatchback',
                'Mazda 3 Sedan',
                'Mazda CX-8',
                'Mazda 6 Sedan',
                'Mazda CX-30',
                'Mazda CX-5',
                'Mazda MX 5 RF',
                'Mazda 2 Sedan',
                'Mazda CX-60',
                'Mazda 6 Estate',
                'Mazda MX-30',
                'Mazda CX-80',
            ],
            'Isuzu' => [
                'Isuzu Traga',
                'Isuzu MuX',
                'Isuzu D Max',
            ],
            'Mercedes-Benz' => [
                'Mercedes Benz G-Class',
                'Mercedes Benz GLE-Class',
                'Mercedes Benz C-Class Sedan',
                'Mercedes Benz GLB-Class',
                'Mercedes Benz CLA-Class',
                'Mercedes Benz S-Class',
                'Mercedes Benz GLA',
                'Mercedes Benz GLS-Class',
                'Mercedes Benz E-Class',
                'Mercedes Benz AMG GT',
                'Mercedes Benz V-Class',
                'Mercedes Benz EQS',
                'Mercedes Benz A-Class Sedan',
                'Mercedes Benz A-Class',
                'Mercedes Benz GLC-Class',
                'Mercedes Benz Sprinter',
                'Mercedes Benz Maybach S-Class',
                'Mercedes Benz Maybach GLS-Class',
                'Mercedes Benz CLS-Class',
                'Mercedes Benz SL-Class',
                'Mercedes Benz EQE',
                'Mercedes Benz EQB',
                'Mercedes Benz CLE Coupe',
                'Mercedes Benz EQA',
                'Mercedes Benz EQS SUV',
                'Mercedes Benz EQE SUV',
                'Mercedes Benz G-Class Electric',
            ],
            'Nissan' => [
                'Nissan Livina',
                'Nissan X Trail',
                'Nissan Serena',
                'Nissan Magnite',
                'Nissan Serena e-Power',
                'Nissan Leaf',
                'Nissan Terra',
                'Nissan Kicks e-Power',
            ],
            'DFSK' => [
                'DFSK Glory 560',
                'DFSK Supercab',
                'DFSK Gelora',
                'DFSK Seres E1',
                'DFSK Glory i-Auto',
                'DFSK Gelora Electric',
            ],
            'Renault' => [
                'Renault KWID',
                'Renault Triber',
                'Renault Kiger',
            ],
            'Volkswagen' => [
                'Volkswagen Golf GTI',
                'Volkswagen Tiguan Allspace',
                'Volkswagen ID Buzz',
                'Volkswagen T-Cross',
            ],
            'Lexus' => [
                'Lexus RX',
                'Lexus LX',
                'Lexus RZ',
                'Lexus NX',
                'Lexus LBX',
                'Lexus LS',
                'Lexus LC',
                'Lexus UX',
                'Lexus ES',
                'Lexus LM',
            ],
            'Jeep' => [
                'Jeep Wrangler',
            ],
            'Land Rover' => [
                'Land Rover Range Rover Evoque',
                'Land Rover Defender',
                'Land Rover Discovery',
                'Land Rover Range Rover Velar',
                'Land Rover Range Rover Sport',
                'Land Rover Range Rover',
                'Land Rover Discovery Sport',
            ],
            'Audi' => [
                'Audi TT Coupe',
                'Audi TTS Coupe',
                'Audi R8',
                'Audi A6',
                'Audi A7',
                'Audi Q5',
                'Audi RS5',
                'Audi Q7',
                'Audi Q3',
                'Audi A5',
                'Audi Q8',
                'Audi A5 Sportback',
                'Audi Q3 Sportback',
                'Audi A8 L',
                'Audi RS 4 Avant',
            ],
            'Tata' => [
                'Tata Xenon',
                'Tata Super Ace',
                'Tata Intra V20',
            ],
            'MINI' => [
                'MINI Countryman',
                'MINI 5 Door',
                'MINI 3 Door',
                'MINI Electric',
                'MINI Electric Countryman',
                'MINI Electric Cooper',
                'MINI New Countryman',
                'MINI Cooper',
                'MINI Electric Aceman',
                'MINI All New 5 Door',
            ],
            'Peugeot Mobil' => [
                'Peugeot 3008',
                'Peugeot 5008',
                'Peugeot 2008',
            ],
            'Lamborghini' => [
                'Lamborghini Huracan',
                'Lamborghini Revuelto',
                'Lamborghini Urus',
            ],
            'Porsche' => [
                'Porsche 911',
                'Porsche Macan',
                'Porsche Taycan',
                'Porsche Panamera',
                'Porsche Cayenne',
                'Porsche 718',
                'Porsche Macan Electric',
            ],
            'Ferrari' => [
                'Ferrari SF90 Stradale',
                'Ferrari F8 Spider',
                'Ferrari 812 GTS',
                'Ferrari F8 Tributo',
                'Ferrari Portofino M',
                'Ferrari SF90 Spider',
                'Ferrari Roma',
                'Ferrari 296 GTB',
                'Ferrari 296 GTS',
            ],
            'Aston Martin' => [
                'Aston Martin Vantage',
                'Aston Martin DB11',
                'Aston Martin Vanquish',
                'Aston Martin Rapide S',
            ],
            'Mclaren' => [
                'Mclaren 765LT',
                'Mclaren 650S',
                'Mclaren Senna',
                'Mclaren 720S Spider',
                'Mclaren 720S',
                'Mclaren P1',
                'Mclaren 570S',
                'Mclaren 540C',
                'Mclaren 12C',
                'Mclaren Artura',
                'Mclaren 765LT Spider',
                'Mclaren 675LT',
                'Mclaren 650 S Spider',
                'Mclaren 570GT',
                'Mclaren GT',
                'Mclaren 750S',
                'Mclaren 750S Spider',
                'Mclaren Artura Spider',
                'Mclaren GTS',
                'Mclaren Speedtail',
                'Mclaren Elva',
                'Mclaren Solus GT',
                'Mclaren 600LT',
                'Mclaren 600LT Spider',
                'Mclaren 675LT Spider',
                'Mclaren 570S Spider',
                'Mclaren 650S Can-Am Spider',
                'Mclaren 12C Spider',
            ],
            'Jaguar' => [
                'Jaguar F Type',
                'Jaguar XF',
                'Jaguar E-PACE',
                'Jaguar F PACE',
                'Jaguar I-PACE',
            ],
            'Rolls Royce' => [
                'Rolls Royce Spectre',
                'Rolls Royce Phantom',
                'Rolls Royce Wraith',
                'Rolls Royce Ghost',
            ],
            'Volvo' => [
                'Volvo XC90 PHEV',
                'Volvo XC60 PHEV',
                'Volvo EX30 EV',
                'Volvo EX40 EV',
                'Volvo EC40 EV',
            ],
            'Maserati' => [
                'Maserati GranCabrio',
                'Maserati Ghibli',
                'Maserati GranTurismo',
                'Maserati Quattroporte',
            ],
            'Bentley' => [
                'Bentley Continental',
                'Bentley Flying Spur',
                'Bentley Bentayga',
            ],
            'Fiat' => [
                'Fiat 500C',
            ],
            'Ford' => [
                'Ford Everest',
                'Ford Ranger',
                'Ford Ranger Raptor',
            ],
            'Geely' => [
                'Geely EX5',
            ],
            'Subaru' => [
                'Subaru BRZ',
                'Subaru Crosstrek',
                'Subaru WRX',
                'Subaru Forester',
                'Subaru WRX Wagon',
                'Subaru Outback',
            ],
            'Tesla' => [
                'Tesla Model X',
                'Tesla Model S',
                'Tesla Model 3',
            ],
            'Mahindra' => [
                'Mahindra Scorpio Pikup',
                'Mahindra Bolero Maxitruck',
            ],
            'MG' => [
                'MG 4 EV',
                'MG ZS',
                'MG 5 GT',
                'MG VS HEV',
                'MG HS',
                'MG ZS EV',
                'MG Cyberster',
            ],
            'Maxus' => [
                'Maxus Mifa 9',
                'Maxus Mifa 7',
            ],
            'Chery' => [
                'Chery OMODA 5',
                'Chery OMODA E5',
                'Chery TIGGO 8',
                'Chery TIGGO 8 PRO',
                'Chery TIGGO 7 PRO',
                'Chery TIGGO 8 PRO MAX',
                'Chery OMODA 5 GT',
                'Chery J6',
                'Chery Tiggo Cross',
                'Chery Tiggo 8 CSH',
            ],
            'Citroen' => [
                'Citroen C3 Aircross',
                'Citroen E-C3',
                'Citroen E-C4',
                'Citroen C5 Aircross',
                'Citroen C3',
            ],
            'ESEMKA' => [
                'ESEMKA BIMA 1.3',
                'ESEMKA BIMA 1.2',
            ],
            'Neta' => [
                'Neta V-II',
                'Neta X',
                'Neta V',
            ],
            'GWM' => [
                'GWM Tank 300 HEV',
                'GWM Tank 500 HEV',
                'GWM Haval H6 HEV',
                'GWM Ora 03 BEV',
                'GWM Haval Jolion',
            ],
            'BYD' => [
                'BYD M6',
                'BYD Seal',
                'BYD Dolphin',
                'BYD Atto 3',
                'BYD Denza D9',
                'BYD Sealion 7',
            ],
            'VinFast' => [
                'VinFast VF 5',
                'VinFast VF e34',
                'VinFast VF 6',
                'VinFast VF 3',
            ],
            'BAIC' => [
                'BAIC BJ40 Plus',
                'BAIC X55 II',
            ],
            'GAC' => [
                'GAC Aion Y Plus',
                'GAC Aion Hyptec HT',
                'GAC Aion ES',
                'GAC Aion V',
            ],
            'Jetour' => [
                'Jetour Dashing',
                'Jetour X70 Plus',
            ],
            'JAECOO' => [
                'JAECOO J7',
                'JAECOO J7 SHS',
            ],
            'ZEEKR' => [
                'ZEEKR 009',
            ],
            'ALETRA' => [
                'ALETRA L8 EV',
            ],
            'Honri' => [
                'Honri Boma',
            ],
            'Polytron Mobil' => [
                'Polytron G3',
            ],
        ];

        foreach ($data as $brandName => $modelNames) {
            $brand = VehicleBrand::where('name', $brandName)->first();

            if (!$brand) {
                continue;
            }

            foreach ($modelNames as $modelName) {
                VehicleModel::firstOrCreate(
                    ['name' => $modelName, 'vehicle_brand_id' => $brand->id]
                );
            }
        }
    }
}
