<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VehicleModel;
use App\Models\VehicleBrand;
use App\Models\VehicleType;

class VehicleModelSeeder extends Seeder
{
    public function run(): void
    {
        // Pastikan sudah ada data brand dan type
        if (VehicleBrand::count() === 0 || VehicleType::count() === 0) {
            $this->command->warn('VehicleBrand or VehicleType belum ada. Jalankan seeder-nya dulu.');
            return;
        }

        // Contoh data manual
        $models = [
            ['name' => 'Honda Vario 125', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Scoopy', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Beat', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda PCX160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Beat Street', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CRF150L', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Stylo 160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Vario 160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda ADV 160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Supra GTR 150', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Vario 125', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Sonic 150R', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Stylo 160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Vario 160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda ADV 160', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Supra GTR 150', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Sonic 150R', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Genio', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Revo', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CBR150R', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CBR250RR', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Supra X 125 FI', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CB150 Verza', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CB150R Streetfire', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CRF250Rally', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Forza 250', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CB150X', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda EM1 E', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CB650R', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CRF250L', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Rebel', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CB500X', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Super Cub C125', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda ST125 Dax', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CT125', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CBR1000RR-R', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CRF1100L Africa Twin', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda XL750 Transalp', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Monkey', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda ICON e:', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda CUV e:', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Goldwing', 'brand' => 'Honda', 'type' => 'Motor'],
            ['name' => 'Honda Rebel 1100', 'brand' => 'Honda', 'type' => 'Motor'],

            ['name' => 'Yamaha Jupiter Z1', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Fino 125', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Nmax', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Fazzio', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Mio M3 125', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Aerox Connected', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Grand Filano Hybrid Connected', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha XRide 125', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Nmax Connected', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha XSR 155', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Vega Force', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha MT-25', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Aerox Connected ABS', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Xmax Connected', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Gear 125', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha R15 Connected', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Vixion', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Lexi LX 155', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha FreeGo', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha MT-15', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Vixion R', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha YZ125X', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha YZF R25', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Freego Connected', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha YZ250', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Aerox Alpha', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Gear Ultima', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha WR155 R', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha MX King', 'brand' => 'Yamaha', 'type' => 'Motor'],
            ['name' => 'Yamaha Nmax Turbo', 'brand' => 'Yamaha', 'type' => 'Motor'],

            ['name' => 'Kawasaki KX 65', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki W175', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja ZX-25R', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja 250', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 150 SM', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 150', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki D-Tracker', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 140R', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z125 PRO', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 150 SM SE', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja ZX-25RR', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki W175TR', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 250', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z900', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja H2', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z1000', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja ZX-4RR', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Versys X 250', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX110R', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Versys 1000', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 230', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 230 SM', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Vulcan S', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki NINJA E-1', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Versys 650', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KLX 150 S', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KX 112', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KX 250', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KX 450', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja ZX-6R ABS', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki ELIMINATOR', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z900RS', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Ninja ZX10-R', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KX 85', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z900RS CAFE', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Stockman', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z E-1', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KX 250X', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki KX 450X', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki W800', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki Z900 SE', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki W230', 'brand' => 'Kawasaki', 'type' => 'Motor'],
            ['name' => 'Kawasaki MEGURO S1', 'brand' => 'Kawasaki', 'type' => 'Motor'],

            ['name' => 'Suzuki Satria F150', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki GSX R150', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki Burgman Street 125 EX', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki NEX II', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki GSX S150', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki NEX Crossover', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki Address', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki V-Strom 250 SX', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki Avenis', 'brand' => 'Suzuki', 'type' => 'Motor'],
            ['name' => 'Suzuki Gixxer SF 250', 'brand' => 'Suzuki', 'type' => 'Motor'],

            ['name' => 'Benelli Zafferano 250', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Motobi 200 Evo', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Patagonian Eagle 250', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Motobi 200', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Motobi 152', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Patagonian 250 EFI', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Panarea 125', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli TNT 135', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli TRK251', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Imperiale 400', 'brand' => 'Benelli', 'type' => 'Motor'],

            ['name' => 'Benelli TRK 502X', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Leoncino 250', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli 502C', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli TNT 249S', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli TNT 600i', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Dong', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli TNT 1130', 'brand' => 'Benelli', 'type' => 'Motor'],
            ['name' => 'Benelli Leoncino 500', 'brand' => 'Benelli', 'type' => 'Motor'],

            ['name' => 'KTM RC 390', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM Duke 200', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 450 SX-F Factory Edition', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM RC 200', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 250 SX-F Troy Lee Designs', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM Duke 390', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 250 Adventure', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 300 EXC Hardenduro', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 390 Adventure', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM Duke 250', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 300 XC-W Hardenduro', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 890 Duke R', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM Brabus 1300 R Masterpiece Edition', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 890 Adventure R Rally', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 890 Adventure', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM 890 SMT', 'brand' => 'KTM', 'type' => 'Motor'],
            ['name' => 'KTM RC 250', 'brand' => 'KTM', 'type' => 'Motor'],

            ['name' => 'TVS Rockz', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Dazz', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Neo XR', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS XL 100', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Callisto', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Ronin', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Max 125 Semi Trail', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Max 125 Sport', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS Ntorq 125', 'brand' => 'TVS', 'type' => 'Motor'],
            ['name' => 'TVS iQube S', 'brand' => 'TVS', 'type' => 'Motor'],

            ['name' => 'BMW R Nine T', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW G 310 R', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW G 310 GS', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW S 1000 RR', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R Nine T Scrambler ', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW S 1000 XR', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW F 900 R', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW K 1600 B', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 1250 GS', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW M 1000 RR', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW C 400 X', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 1300 GS', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 1250 GS Adventure', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R Nine T Urban G/S', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW K 1600 B Grand America', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW C 400 GT', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 18 Classic', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW F 850 GS Adventure', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 12', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R12 S', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW CE 04', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 18', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW CE 02', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 12 NineT', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW F 900 GS', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW M 1000 R', 'brand' => 'BMW', 'type' => 'Motor'],
            ['name' => 'BMW R 1300 GS Adventure', 'brand' => 'BMW', 'type' => 'Motor'],

            ['name' => 'Viar Cross X 100 Mini Trail', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar Cross X 70 Mini Trail', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar EV1', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar ER1', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar NX', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar V3', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar U3', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar C3X', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar Caraka', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar A2', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar Akasha3', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar UNO3', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar Q1', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar N1', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar CrossX 150DB', 'brand' => 'Viar', 'type' => 'Motor'],
            ['name' => 'Viar UNO4', 'brand' => 'Viar', 'type' => 'Motor'],

            ['name' => 'Vespa Sprint', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa LX', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa Primavera', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa GTS 150', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa GTS Super Sport 150', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa GTV', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa ELETTRICA', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa Sprint', 'brand' => 'Vespa', 'type' => 'Motor'],
            ['name' => 'Vespa Sprint', 'brand' => 'Vespa', 'type' => 'Motor'],

            ['name' => 'Royal Enfield Classic 350', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Meteor', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Himalayan', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Hunter 350', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Interceptor 650', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Continental GT 650', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Super Meteor 650', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Bullet 350', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Shotgun 650', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Scram 411', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Guerrilla 450', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
            ['name' => 'Royal Enfield Himalayan 450', 'brand' => 'Royal Enfield', 'type' => 'Motor'],
        ];

        foreach ($models as $model) {
            $brand = VehicleBrand::where('name', $model['brand'])->first();
            $type = VehicleType::where('name', $model['type'])->first();

            if ($brand && $type) {
                VehicleModel::firstOrCreate([
                    'name' => $model['name'],
                    'vehicle_brand_id' => $brand->id,
                    'vehicle_type_id' => $type->id,
                ]);
            }
        }
    }
}
